_core/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import CustomLoginView, CustomSignupView

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/signup/', CustomSignupView.as_view(), name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('user/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payment.urls')),
    path('messages/', include('direct_messages.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

direct_messages/urls.py
from django.urls import path, include
from . import views

app_name = 'direct_messages'

urlpatterns = [
    path('', views.chat_view, name='chat'),
    path('<int:recipient_id>/', views.chat_view, name='chat'),
    path('send-message/<str:username>/',
         views.send_message, name='send_message'),
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('not-available/', views.under_dev, name='not_available'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('pricing/', views.pricing, name='pricing'),
    path('terms/', views.terms, name='terms'),
    path('privacy-policy/', views.priv_pol, name='privpol'),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [

    path('create/<str:prd_id>', views.create_edit_product, name='create'),
    path('create', views.create_edit_product, name='create'),
    path('products-list/<str:provider_id>', views.view_products, name='all'),
    path('products-list', views.view_products, name='all'),
    path('delete-product/<int:prd_id>', views.delete_product, name='delete'),
    path('details/<int:prd_id>', views.view_product_detail, name='item-view'),
    path('search', views.search_products, name='search'),
    path('view-cart', views.view_shopping_cart, name='view-cart'),
    path('add-to-cart/<str:prd_id>/<int:quantity>',
         views.add_product, name='add-cart'),
    path('add-to-cart/<str:prd_id>/<str:go_to>/<int:quantity>',
         views.add_product, name='add-cart'),
    path('remove-item/<str:prd_id>/<int:quantity>',
         views.remove_product, name='remove'),

]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<int:user_id>', views.profile, name='user_profile'),
    path('profile', views.profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('dashboard', views.dashboard, name='dashboard'),
]

templates/widgets/alert.html
{# Check if there are any messages to display #}
{% if not request.resolver_match.url_name == "chat" %}
    {% if messages %}
        {# Loop through each message in the messages list #}
        {% for message in messages %}
            {# Display the message within a Bootstrap alert component #}
            <div class="alert alert-{{ message.tags }}">
                {# Display the message text itself #}
                {{ message }}
                
                {# Add a close button for dismissing the alert (Bootstrap functionality) #}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endif %}



{% comment %} 
    messages.add_message(request, messages.SUCCESS, 'This is a success message')
{% endcomment %}

templates/widgets/footer.html
<footer>
  <div class="container">
    <div class="row">
      <!-- About Section -->
      <div class="col-md-4">
        <h3>About Us</h3>
        <p>
          Our mission is to simplify supply chain management by offering user-friendly, tailored web solutions for suppliers and businesses. Whether you need to connect with new partners or streamline your current operations, we're here to help every step of the way and deliver results that matter.</p>
      </div>
  
      <!-- Navigation Links -->
      <div class="col-md-4">
        <div class="col">
          <h3>Quick Links</h3>
        </div>
        <div class="col d-md-flex">
          <div class="col-md-6">
            <ul class="list-unstyled">
              {# Use Django's url tag instead of Flask's url_for #}
              <li>
                <a href="{% url 'main:home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'main:about' %}">About Us</a>
              </li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li>
                <a href="{% url 'main:faq' %}">FaQ</a>
              </li>
              <li>
                <a href="{% url 'main:terms' %}">Terms & Conditions</a>
              </li>
              <li>
                <a href="{% url 'main:privpol' %}">Privacy Policy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
  
      <!-- Contact Info -->
      <div class="col-md-4">
        <h3>Contact Us</h3>
        <ul class="list-unstyled">
          <li>Email: contact@example.com</li>
          <li>Phone: +1 234 567 890</li>
          <li>Address: 123 Fake Street, City, Country</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/widgets/navbar.html
{% load static %}
<nav>
    <div class="container navbar navbar-expand-lg">
        <div class="container-fluid">
            <!-- Logo -->
            <div class="navbar-header order-md-0">
                <h1 class="d-none">Red-Bazaar.com</h1>
                <a class="navbar-brand" href="{% url 'main:home' %}">
                    <img src="{% static 'imgs/logo-01.ico' %}" height="90" alt="Main LOGO">
                </a>
            </div>

            <!-- Toggle Button for Mobile -->
            <span class="navbar-toggler order-md-3 order-2 border-0 ms-2" role="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list fs-1"></i>
            </span>

            {% if user.is_authenticated %}
            <!-- Cart and Messages Buttons: Always Visible -->
                <div class="d-flex align-items-center justify-content-center gap-3 order-md-2 order-1 ms-auto ms-md-0 me-md-3">
                    {% if user.role == 'BUY' %}
                    <!-- Cart Button -->
                    <a href="{% url 'products:view-cart' %}" class="position-relative nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="View Cart" aria-label="View Cart">
                        <i class="bi bi-cart fs-3"></i>
                        {% if cart_items_count > 0 %}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ cart_items_count }}
                        </span>
                        {% endif %}
                    </a>
                    {% elif user.role == 'SUP'%}
                    <!-- Add Item Button -->
                    <a href="{% url 'products:create' %}" class="position-relative nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Add an Item" aria-label="Add item">
                        <i class="bi bi-plus-square fs-3"></i>
                    </a>
                    {% endif %}

                    <!-- Messages Button -->
                    <a href="{% url 'direct_messages:chat' %}" class="position-relative nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="View Messages" aria-label="Open chat">
                        <i class="bi bi-chat fs-3"></i>
                        {% if new_messages_count > 0 %}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ new_messages_count }}
                        </span>
                        {% endif %}
                    </a>
                </div>
            {% endif %}

            <!-- Navbar Links -->
            <div class="collapse navbar-collapse justify-content-center order-lg-1 order-3" id="navbarNav">
                <ul class="navbar-nav text-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                    </li>
                    {# Logged in user Links to display #}
                    {% if user.is_authenticated %}
                        {% if  user.role != 'STAFF' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:all' %}">All Products</a>
                        </li>
                    {# Not logged in user Links to display #}
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:terms' %}">Terms & Conditions</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Log In/Sign UP</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_login' %}">
                                        <i class="bi bi-caret-right-fill"> USER Login</i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_signup' %}">
                                        <i class="bi bi-caret-right-fill"> USER Registration</i>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>

                <!-- Search Bar for Mobile (Inside Dropdown) -->
                <div class="d-flex d-lg-none justify-content-center mt-3">
                    <form class="form-inline d-flex" action="{% url 'products:search' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-success" type="submit" aria-label="Search button"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>

            <!-- Search Bar for Desktop -->
            <div id="desktop-search" class="d-none d-lg-flex justify-content-end order-md-3 ms-auto">
                <form class="form-inline d-flex flex-row-reverse" action="{% url 'products:search' %}" method="GET">
                    <button class="btn btn-success" type="submit"  aria-label="Search button"><i class="bi bi-search"></i></button>
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                </form>
            </div>
        </div>
    </div>
</nav>
<!-- INFO messages -->
{% include "widgets/alert.html" %}